// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZyeulwyynwD692pTnTvpkC4va5z8Ncc',
    appId: '1:1008725899775:web:1523fe714a3ec943554fca',
    messagingSenderId: '1008725899775',
    projectId: 'onlinenotepad-5c1c2',
    authDomain: 'onlinenotepad-5c1c2.firebaseapp.com',
    storageBucket: 'onlinenotepad-5c1c2.appspot.com',
    measurementId: 'G-KHQFFT2QVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV5CEcRd-qYD1C46m-h5ydEW_oEZQ-B7g',
    appId: '1:1008725899775:android:6b0ef3670f896613554fca',
    messagingSenderId: '1008725899775',
    projectId: 'onlinenotepad-5c1c2',
    storageBucket: 'onlinenotepad-5c1c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTRH6LGGCxTir9YCX5YzOTOJfHUEoVLEM',
    appId: '1:1008725899775:ios:88427df7abebf90b554fca',
    messagingSenderId: '1008725899775',
    projectId: 'onlinenotepad-5c1c2',
    storageBucket: 'onlinenotepad-5c1c2.appspot.com',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTRH6LGGCxTir9YCX5YzOTOJfHUEoVLEM',
    appId: '1:1008725899775:ios:88427df7abebf90b554fca',
    messagingSenderId: '1008725899775',
    projectId: 'onlinenotepad-5c1c2',
    storageBucket: 'onlinenotepad-5c1c2.appspot.com',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZyeulwyynwD692pTnTvpkC4va5z8Ncc',
    appId: '1:1008725899775:web:31d107119fc2bbef554fca',
    messagingSenderId: '1008725899775',
    projectId: 'onlinenotepad-5c1c2',
    authDomain: 'onlinenotepad-5c1c2.firebaseapp.com',
    storageBucket: 'onlinenotepad-5c1c2.appspot.com',
    measurementId: 'G-3G8XMYS2WX',
  );
}
